name: PR Checks

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  commits:
    name: Commits
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@v4
        with:
          command: check
          args: --from-latest-tag

  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Verify dependencies and lockfile
        run: deno install --frozen

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Check formatting
        run: deno fmt --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Run lint checks
        run: deno lint

  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Type check
        run: deno check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Check docs
        run: deno doc --lint src/ && deno check --doc-only src/

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Run tests
        run: deno test tests/ --coverage=.coverage --parallel --quiet --fail-fast --allow-all --permit-no-files

  security:
    name: Security
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Audit dependencies
        run: deno audit --frozen --level=high
